reasoning_gym:
  dataset_size: 20000
  developer_prompt: DeepSeekZero
  datasets:
    complex_arithmetic:
      weight: 1
    intermediate_integration:
      weight: 1
    polynomial_equations:
      weight: 1
    polynomial_multiplication:
      weight: 1
    simple_equations:
      weight: 1
    simple_integration:
      weight: 1

curriculum:
  enabled: False
